services:
  server:
    build:
      context: .
    ports:
      - 80:80
    environment:
      SERVER_PORT: 80
      DB_URL: jdbc:mysql://database:3306/tech_sprint_solutions_db_dev
      DB_USER: mysql
      DB_PASSWORD: password
      DB_DRIVER_CLASS: com.mysql.cj.jdbc.Driver
      DB_TIMEOUT: 30000
      DB_MAXIMUM_POOL_SIZE: 3
      DB_DIALECT: org.hibernate.dialect.MySQLDialect
      DB_DDL_AUTO: update
      DB_OPEN_VIEW: false
      SPRING_SECURITY_JWT_SIGNATURE: CCgbVvfCkAx884yCIadHEOSiO3wOw3AY1OCFvXgwD2TNTxDgTuXi3OrDaH4rzEGS0J6gynpO8K13nT70pbAaDGQdhEOk8G6JRtdz
      SPRING_PROFILES_ACTIVE: dev
      SERVER_SERVLET_CONTEXT_PATH: /tech-sprint-solutions

  database:
    container_name: database
    image: bitnami/mysql:8.0.26-debian-10-r60
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_USER: mysql
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./src/main/docker/create_databases.sql:/docker-entrypoint-initdb.d/init.sql
