server:
  port: ${SERVER_PORT:8081}
  servlet:
    context-path: ${SERVER_SERVLET_CONTEXT_PATH:/tech-sprint-solutions}

springdoc:
  show-actuator: ${SPRING_DOC_ACTUATOR:true}

jwt:
  public:
    key: -----BEGIN PUBLIC KEY----- MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzifYmPq12OI2mEGI1GfM FhPw7aZ5Vn3B8qAVc8e28BOOb329gAZ1VBNfOjGe+9OTsGutlm1WYBQj7O0ZTuEl wvH+dEO6Q8dyNek1yBiVTT/Ok/aDzVGOHdS0v0tMVfQA8jxmHNVz807YVmE36vCN qv0nmx5jQAMGNI77N/q54LNHBwhWBOsvOP/yQBRappONColLK5GBoxHtIKA2AT6t c8B1pPW9GSfLq4xHmiY25bgaMaBMwPLKFMw+syzwW6sn97xzkH4/zh6y+C/onX3z Qw3TNNhnKg1LUGCGj2aIIOj3xbr2VYINx1U+TIW2S+gPV0gLAxcRiNHqkCP/PsSD wQIDAQAB -----END PUBLIC KEY-----
  private:
    key: -----BEGIN PRIVATE KEY----- MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDOJ9iY+rXY4jaY QYjUZ8wWE/DtpnlWfcHyoBVzx7bwE45vfb2ABnVUE186MZ7705Owa62WbVZgFCPs 7RlO4SXC8f50Q7pDx3I16TXIGJVNP86T9oPNUY4d1LS/S0xV9ADyPGYc1XPzTthW YTfq8I2q/SebHmNAAwY0jvs3+rngs0cHCFYE6y84//JAFFqmk40KiUsrkYGjEe0g oDYBPq1zwHWk9b0ZJ8urjEeaJjbluBoxoEzA8soUzD6zLPBbqyf3vHOQfj/OHrL4 L+idffNDDdM02GcqDUtQYIaPZogg6PfFuvZVgg3HVT5MhbZL6A9XSAsDFxGI0eqQ I/8+xIPBAgMBAAECggEAIu12UYjciWfeJxKnW5FQbwcm4SS81w4Mb452w/x4vpkZ n0MW+ZtegoWbszDYBkN0+MVtjhhtM28GHSyYhpg3vR0h5tHYu4YNkBu4bHPZy9I9 Li1sbDtekChLDUP1JXTnOiNIi6cQc48OsSfcgPYLkoY8kRfnad95TCtTXcshdfOr qBpJF+C4kwaU5zn11HT0Ljfmjvi2huyzK9NSd/w0xunfHg7GYjORqGkwq3VitrzI Nh4Si1VT0n8shCG5bzLxrdEdHtWAQWFCguRn2iSVk1vd4oFLmp/SPge8sSNfTJ+C OBGX2oLi+36SRJ8Z2+dXpNRscGqD2daL1HcG9P9hVwKBgQD8yertdTu+FyX63ZjX Ns3jkev8t/HYdB/ka5ONnFfreuauUCYFh5vjZwxbA14GacsyQNhEy/3u/+IJVrIO pPSkUi7NFDXzrI7QwAn5eT3nRQrncqY34eeTCgjO4vL8Kj5hn5MYgnt1C9DmBmd2 UXSFntvRLOOlVnTd0K+iQaokEwKBgQDQxkZuhHYgVsujiQMIuVwTJ6npXdFzLAkB xFACLYdklPJPLXsOu0ReUE7KWQOldG6wMadhXpEFRyFnWcblJpsC8XgkBoWreygQ 4XjKgTxUb1IIAT/dpKMrYl4QcPo6hOEAeBPJZPyIbFqJ4rFtUUNleQSMoj7l9S/y 4/psRiurWwKBgDIOBW/Jo+/LA6E+GdKbrn8eWN0syz2yGNKRHqGO0LX3GxBvHGhB 5vNLZ13qN8cLUcn8nxZYUkrt7iMtQIq3zR1wjIXdN6WtiIX7UL5ObJyLxlH4GMO9 /q3V8dKNi9G0x69q+qSCydFuaonxwLDkBi+jOiGcQuNtUCzP8sctO3RzAoGBAJCG MYugNwX8D8yNtIP9jTfVZVIfmDbabQHEHH7ldayzT2pwWZfBG3sOrPx20odfKqDe Priw9kNpEj6xb3aCWxyWfEy0FyS2hO3qp+vHuzPYPDk+ZC/TIQGPfv5yt0Z7Zick +M2aExd9qs95FspOTxGXzQZt6ozWRvMlzt3VVbWxAoGBALRvbzHICjec9b4qKBWC Gc/bcJJr3jqjTbRHUA0HQmhsDfsCwWcX+w+7rdVQA9uUFfU1HoxvG71lXQ1JOV9g PnyCMvfyNUrn/jYpfrRy+X3h4uJANLeJwo+uZ+IqHVxWrNd0uVJqLaU+dX4lNkhW 8MpIMnkFQA90HFj0WX00pwiF -----END PRIVATE KEY-----

spring:

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/tech_sprint_solutions_db_loc}
    username: ${DB_USER:mysql}
    password: ${DB_PASSWORD:password}
    driver-class-name: ${DB_DRIVER_CLASS:com.mysql.cj.jdbc.Driver}
    hikari:
      connection-timeout: ${DB_TIMEOUT:30000}
      maximum-pool-size: ${DB_MAXIMUM_POOL_SIZE:3}

  jpa:
    hibernate:
      ddl-auto: ${DB_DDL_AUTO:update}
    open-in-view: ${DB_OPEN_VIEW:false}

  security:
    jwt:
      signature: ${SPRING_SECURITY_JWT_SIGNATURE:TESTE}

  autoconfigure.exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

logging:
  level:
    org.apache.catalina.core: WARN
    org.springframework.security.web: WARN
    com.zaxxer.hikari: WARN
    org.springframework.data.repository.config.RepositoryConfigurationDelegate: WARN
    org.hibernate: WARN
    org.hibernate.jpa.internal.util: WARN
    org.springframework.orm.jpa.persistenceunit: WARN
    org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean: WARN
    org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext: WARN
    org.springframework.web.servlet: WARN
    org.springframework.boot.actuate.endpoint.web: WARN


