server:
  port: ${SERVER_PORT}
  servlet:
    context-path: ${SERVER_SERVLET_CONTEXT_PATH}

spring:

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS}
    hikari:
      connection-timeout: ${DB_TIMEOUT}
      maximum-pool-size: ${DB_MAXIMUM_POOL_SIZE}

  jpa:
    properties:
      hibernate:
        dialect: ${DB_DIALECT}
    hibernate:
      ddl-auto: ${DB_DDL_AUTO}
    open-in-view: ${DB_OPEN_VIEW}

  security:
    jwt:
      signature: ${SPRING_SECURITY_JWT_SIGNATURE}

  autoconfigure.exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
